pipeline:
    name: test-pipe
    identifier: testpipe
    allowStageExecutions: false
    projectIdentifier: TestMantriProject
    orgIdentifier: MantriOrg
    tags: {}
    stages: []
    flowControl:
        barriers:
            - name: test barrier
              identifier: test_barrier
            - name: random barrier
              identifier: random_barrier
